// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/abilities": {
            "get": {
                "description": "Returns allowed actions for the user in the specified org path",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "abilities"
                ],
                "summary": "Get user abilities for an org path",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Organization path",
                        "name": "org_path",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Comma-separated actions to check",
                        "name": "actions",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.abilitiesResp"
                        }
                    }
                }
            }
        },
        "/api/abilities/where": {
            "get": {
                "description": "Returns org paths where the user has permission for the specified action",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "abilities"
                ],
                "summary": "List org paths where user can perform an action",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Action to check",
                        "name": "action",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/auth/login": {
            "post": {
                "description": "Authenticates user and returns JWT access token",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Login",
                "parameters": [
                    {
                        "description": "Login credentials",
                        "name": "loginReq",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.loginReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.loginResp"
                        }
                    }
                }
            }
        },
        "/api/auth/me": {
            "get": {
                "description": "Returns claims of the authenticated user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Get current user info",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer JWT token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/memberships": {
            "get": {
                "description": "List memberships with optional filters",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "memberships"
                ],
                "summary": "List memberships",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User reference (_id, id, student_id)",
                        "name": "user",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Organization path",
                        "name": "org_path",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Position key",
                        "name": "position_key",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Membership status",
                        "name": "status",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/api.MembershipDoc"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "Assign a user to an org unit and position",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "memberships"
                ],
                "summary": "Create membership",
                "parameters": [
                    {
                        "description": "Membership info",
                        "name": "CreateMembershipReq",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.CreateMembershipReq"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/api.MembershipDoc"
                        }
                    }
                }
            }
        },
        "/api/memberships/{id}": {
            "get": {
                "description": "Get membership by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "memberships"
                ],
                "summary": "Get membership",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Membership ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.MembershipDoc"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete membership by ID",
                "tags": [
                    "memberships"
                ],
                "summary": "Delete membership",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Membership ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    }
                }
            },
            "patch": {
                "description": "Update membership fields (position, status, ended_at)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "memberships"
                ],
                "summary": "Update membership",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Membership ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Fields to update",
                        "name": "UpdateMembershipReq",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.UpdateMembershipReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.MembershipDoc"
                        }
                    }
                }
            }
        },
        "/api/org/units/node": {
            "get": {
                "description": "Get organization unit node by path",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "org_units"
                ],
                "summary": "Get org unit",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Org unit path",
                        "name": "path",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.OrgUnitDoc"
                        }
                    }
                }
            },
            "post": {
                "description": "Create a new organization unit node",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "org_units"
                ],
                "summary": "Create org unit",
                "parameters": [
                    {
                        "description": "Org unit info",
                        "name": "OrgUnitCreate",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.OrgUnitCreate"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/api.OrgUnitDoc"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete organization unit node by path (leaf-only)",
                "tags": [
                    "org_units"
                ],
                "summary": "Delete org unit",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Org unit path",
                        "name": "path",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    }
                }
            },
            "patch": {
                "description": "Update organization unit node by path",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "org_units"
                ],
                "summary": "Update org unit",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Org unit path",
                        "name": "path",
                        "in": "query",
                        "required": true
                    },
                    {
                        "description": "Fields to update",
                        "name": "OrgUnitUpdate",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.OrgUnitUpdate"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.OrgUnitDoc"
                        }
                    }
                }
            }
        },
        "/api/posts": {
            "get": {
                "description": "List posts with pagination and visibility",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "posts"
                ],
                "summary": "List posts",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Page number",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Page size",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "Show all (moderation)",
                        "name": "all",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/api.Post"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "Create a new post",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "posts"
                ],
                "summary": "Create post",
                "parameters": [
                    {
                        "description": "Post info",
                        "name": "createPostDTO",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.createPostDTO"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/api.Post"
                        }
                    }
                }
            }
        },
        "/api/posts/{id}": {
            "get": {
                "description": "Get post by ID (with visibility check)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "posts"
                ],
                "summary": "Get post",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Post ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "boolean",
                        "description": "Show all (moderation)",
                        "name": "all",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.Post"
                        }
                    }
                }
            },
            "put": {
                "description": "Update post fields",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "posts"
                ],
                "summary": "Update post",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Post ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Fields to update",
                        "name": "updatePostDTO",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.updatePostDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.Post"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete post by ID",
                "tags": [
                    "posts"
                ],
                "summary": "Delete post",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Post ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    }
                }
            }
        },
        "/api/posts/{id}/hide": {
            "post": {
                "description": "Hide a post by ID",
                "tags": [
                    "posts"
                ],
                "summary": "Hide post",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Post ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    }
                }
            }
        },
        "/api/posts/{id}/like": {
            "post": {
                "description": "Like a post by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "posts"
                ],
                "summary": "Like post",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Post ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "User ID to like",
                        "name": "likeDTO",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.likeDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.Post"
                        }
                    }
                }
            }
        },
        "/api/posts/{id}/unhide": {
            "post": {
                "description": "Unhide a post by ID",
                "tags": [
                    "posts"
                ],
                "summary": "Unhide post",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Post ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    }
                }
            }
        },
        "/api/posts/{id}/unlike": {
            "post": {
                "description": "Unlike a post by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "posts"
                ],
                "summary": "Unlike post",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Post ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "User ID to unlike",
                        "name": "likeDTO",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.likeDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.Post"
                        }
                    }
                }
            }
        },
        "/policies": {
            "get": {
                "description": "List policies with optional filters",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "policies"
                ],
                "summary": "List policies",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Organization prefix",
                        "name": "org_prefix",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Position key",
                        "name": "position_key",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/api.Policy"
                            }
                        }
                    },
                    "500": {
                        "description": "DB error or decode error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "put": {
                "description": "Upsert (create or update) a policy by position_key, org_prefix, and scope",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "policies"
                ],
                "summary": "Upsert policy",
                "parameters": [
                    {
                        "description": "Policy info",
                        "name": "Policy",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.Policy"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.Policy"
                        }
                    }
                }
            },
            "post": {
                "description": "Create a new policy",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "policies"
                ],
                "summary": "Create policy",
                "parameters": [
                    {
                        "description": "Policy info",
                        "name": "Policy",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.Policy"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/api.Policy"
                        }
                    },
                    "400": {
                        "description": "Invalid body or missing fields",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Insert failed",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete policies by org_prefix and optional position_key",
                "tags": [
                    "policies"
                ],
                "summary": "Delete policy",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Organization prefix",
                        "name": "org_prefix",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Position key",
                        "name": "position_key",
                        "in": "query"
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    }
                }
            }
        },
        "/positions": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "positions"
                ],
                "summary": "List positions",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/api.Position"
                            }
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "positions"
                ],
                "summary": "Create position",
                "parameters": [
                    {
                        "description": "Position",
                        "name": "position",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.Position"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/api.Position"
                        }
                    }
                }
            }
        },
        "/positions/{key}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "positions"
                ],
                "summary": "Get a position by key",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Position key",
                        "name": "key",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.Position"
                        }
                    }
                }
            },
            "put": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "positions"
                ],
                "summary": "Update position",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Position key",
                        "name": "key",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Position (partial)",
                        "name": "position",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.Position"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.Position"
                        }
                    }
                }
            },
            "delete": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "positions"
                ],
                "summary": "Deprecate position (soft delete)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Position key",
                        "name": "key",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    }
                }
            }
        },
        "/users": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Get users with search + keyset pagination",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Search by name/email/student_id",
                        "name": "q",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Page size (default 20, max 100)",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Keyset cursor (base64)",
                        "name": "cursor",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.PagedUsersResponse"
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Create a new user",
                "parameters": [
                    {
                        "description": "User",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.User"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/models.User"
                        }
                    }
                }
            }
        },
        "/users/{id}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Get a single user by numeric app id",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "User numeric id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.User"
                        }
                    }
                }
            },
            "put": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Update an existing user by numeric id",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "User numeric id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "User partial or full",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.User"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.User"
                        }
                    }
                }
            },
            "delete": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Delete a user by numeric id",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "User numeric id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    }
                }
            }
        }
    },
    "definitions": {
        "api.AudienceItem": {
            "type": "object",
            "properties": {
                "org_path": {
                    "type": "string"
                },
                "scope": {
                    "description": "\"exact\" | \"subtree\"",
                    "type": "string"
                }
            }
        },
        "api.CreateMembershipReq": {
            "type": "object",
            "properties": {
                "joined_at": {
                    "type": "string"
                },
                "org_path": {
                    "description": "\"/club/cpsk\"",
                    "type": "string"
                },
                "position_key": {
                    "description": "\"head\", \"member\", \"student\"",
                    "type": "string"
                },
                "user_ref": {
                    "description": "_id hex OR numeric id OR student_id",
                    "type": "string"
                }
            }
        },
        "api.MembershipDoc": {
            "type": "object",
            "properties": {
                "_id": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "ended_at": {
                    "type": "string"
                },
                "joined_at": {
                    "type": "string"
                },
                "org_path": {
                    "type": "string"
                },
                "position_key": {
                    "type": "string"
                },
                "status": {
                    "description": "\"active\" | \"inactive\"",
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "api.OrgUnitCreate": {
            "type": "object",
            "properties": {
                "name": {
                    "description": "{en:\"Computer Engineering\"}",
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "parent_path": {
                    "type": "string"
                },
                "path": {
                    "description": "\"/faculty/eng/com\"",
                    "type": "string"
                },
                "short_name": {
                    "description": "{en:\"COM\", th:\"คอม\"}",
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "slug": {
                    "type": "string"
                },
                "sort": {
                    "type": "integer"
                },
                "status": {
                    "description": "default \"active\"",
                    "type": "string"
                },
                "type": {
                    "description": "\"faculty\"|\"program\"|\"club\"|...",
                    "type": "string"
                },
                "visibility": {
                    "description": "default \"public\"",
                    "type": "string"
                }
            }
        },
        "api.OrgUnitDoc": {
            "type": "object",
            "properties": {
                "ancestors": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "created_at": {
                    "type": "string"
                },
                "depth": {
                    "type": "integer"
                },
                "name": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "parent_path": {
                    "type": "string"
                },
                "path": {
                    "type": "string"
                },
                "short_name": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "slug": {
                    "type": "string"
                },
                "sort": {
                    "type": "integer"
                },
                "status": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "visibility": {
                    "type": "string"
                }
            }
        },
        "api.OrgUnitUpdate": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "short_name": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "slug": {
                    "type": "string"
                },
                "sort": {
                    "type": "integer"
                },
                "status": {
                    "type": "string"
                },
                "visibility": {
                    "type": "string"
                }
            }
        },
        "api.PagedUsersResponse": {
            "type": "object",
            "properties": {
                "items": {
                    "description": "[]models.User"
                },
                "nextCursor": {
                    "type": "string"
                }
            }
        },
        "api.Policy": {
            "type": "object",
            "properties": {
                "actions": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "created_at": {
                    "type": "string"
                },
                "effect": {
                    "description": "\"allow\"",
                    "type": "string"
                },
                "enabled": {
                    "type": "boolean"
                },
                "key": {
                    "type": "string"
                },
                "position_key": {
                    "description": "e.g. \"head\"",
                    "type": "string"
                },
                "scope": {
                    "description": "\"exact\" | \"subtree\"",
                    "type": "string"
                },
                "where": {
                    "$ref": "#/definitions/api.PolicyWhere"
                }
            }
        },
        "api.PolicyWhere": {
            "type": "object",
            "properties": {
                "org_prefix": {
                    "description": "e.g. \"/faculty/\"",
                    "type": "string"
                }
            }
        },
        "api.Position": {
            "type": "object",
            "properties": {
                "constraints": {
                    "type": "object",
                    "properties": {
                        "exclusive_per_org": {
                            "description": "1 per org?",
                            "type": "boolean"
                        },
                        "max_slots": {
                            "description": "capacity (nil = unlimited)",
                            "type": "integer"
                        },
                        "term_days": {
                            "description": "optional expiry window",
                            "type": "integer"
                        }
                    }
                },
                "created_at": {
                    "type": "string"
                },
                "display": {
                    "description": "{ \"en\": \"Head\" }",
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "key": {
                    "description": "stable id (e.g., \"head\")",
                    "type": "string"
                },
                "rank": {
                    "description": "sort order",
                    "type": "integer"
                },
                "scope": {
                    "type": "object",
                    "properties": {
                        "inherit": {
                            "description": "usable by descendants?",
                            "type": "boolean"
                        },
                        "org_path": {
                            "description": "where defined (\"/\" for global)",
                            "type": "string"
                        }
                    }
                },
                "status": {
                    "description": "\"active\" | \"deprecated\"",
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "api.Post": {
            "type": "object",
            "properties": {
                "_id": {
                    "description": "Legacy fields (keep!)",
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "likedBy": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "likes": {
                    "type": "integer"
                },
                "message": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "org_of_content": {
                    "type": "string"
                },
                "posted_as": {
                    "description": "NEW fields (optional)",
                    "allOf": [
                        {
                            "$ref": "#/definitions/api.PostedAs"
                        }
                    ]
                },
                "status": {
                    "description": "\"active\" | \"hidden\" | \"deleted\"",
                    "type": "string"
                },
                "timestamp": {
                    "type": "string"
                },
                "uid": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                },
                "visibility": {
                    "$ref": "#/definitions/api.Visibility"
                }
            }
        },
        "api.PostedAs": {
            "type": "object",
            "properties": {
                "label": {
                    "description": "e.g., \"Head • SMO\"",
                    "type": "string"
                },
                "org_path": {
                    "type": "string"
                },
                "position_key": {
                    "type": "string"
                }
            }
        },
        "api.UpdateMembershipReq": {
            "type": "object",
            "properties": {
                "ended_at": {
                    "type": "string"
                },
                "position_key": {
                    "type": "string"
                },
                "status": {
                    "description": "\"active\" | \"inactive\"",
                    "type": "string"
                }
            }
        },
        "api.Visibility": {
            "type": "object",
            "properties": {
                "access": {
                    "description": "\"public\" | \"org\" | \"custom\"",
                    "type": "string"
                },
                "allow_user_ids": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "audience": {
                    "description": "when Access=\"org\"",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/api.AudienceItem"
                    }
                },
                "deny_user_ids": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "exclude_positions": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "include_positions": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "api.abilitiesResp": {
            "type": "object",
            "properties": {
                "abilities": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "boolean"
                    }
                },
                "org_path": {
                    "type": "string"
                },
                "version": {
                    "type": "string"
                }
            }
        },
        "api.createPostDTO": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "org_of_content": {
                    "type": "string"
                },
                "posted_as": {
                    "description": "Optional",
                    "allOf": [
                        {
                            "$ref": "#/definitions/api.PostedAs"
                        }
                    ]
                },
                "status": {
                    "description": "if omitted -\u003e \"active\"",
                    "type": "string"
                },
                "uid": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                },
                "visibility": {
                    "$ref": "#/definitions/api.Visibility"
                }
            }
        },
        "api.likeDTO": {
            "type": "object",
            "properties": {
                "userId": {
                    "type": "string"
                }
            }
        },
        "api.loginReq": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "api.loginResp": {
            "type": "object",
            "properties": {
                "access_token": {
                    "type": "string"
                }
            }
        },
        "api.updatePostDTO": {
            "type": "object",
            "properties": {
                "likedBy": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "likes": {
                    "type": "integer"
                },
                "message": {
                    "description": "legacy (optional)",
                    "type": "string"
                },
                "org_of_content": {
                    "type": "string"
                },
                "posted_as": {
                    "$ref": "#/definitions/api.PostedAs"
                },
                "status": {
                    "description": "NEW (optional)",
                    "type": "string"
                },
                "visibility": {
                    "$ref": "#/definitions/api.Visibility"
                }
            }
        },
        "models.User": {
            "type": "object",
            "properties": {
                "_id": {
                    "type": "string"
                },
                "advisor_id": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "firstName": {
                    "type": "string"
                },
                "gender": {
                    "type": "string"
                },
                "id": {
                    "description": "numeric app id",
                    "type": "integer"
                },
                "lastName": {
                    "type": "string"
                },
                "roles": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "student_id": {
                    "type": "string"
                },
                "thaiprefix": {
                    "type": "string"
                },
                "type_person": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/api",
	Schemes:          []string{},
	Title:            "My API",
	Description:      "This is my API",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
